[RunParameters]
n_jobs = 4
tries_per_task = 8
evaluator = "webvoyager"
capture_logging = false
max_task_duration_in_s = 360

[RunParameters.task_set]
name = "WebVoyager30"

[Convergence]
max_steps = 20
headless = true
use_anchor = false
